### PR TITLE
contributor added

### PR DESCRIPTION
**Pull request by mansi59054**

### CODE REVIEW

**Comment by Kartik026** [comment]
It seems you have deleted a file `package-lock.json` , please don't delete any file further onwards
And also there's a conflict in your pull request, So first try `git pull` and then again make the changes in the `contributorList.md` and push again

**Comment by srijan-paul** [comment]
> and then again make the changes in the contributorList.md and push again

1. checkout to `mansi59054:dev`
2. `git pull upstream`
3. checkout back to `mansi59054:mansi`
4. `git rebase --interactive dev`
5. commit changes
6. `git push --force-with-lease`

No need to re-do changes, or pull into this PR's branch.
That won't work most of the time if the PR has already been opened.

**Comment by srijan-paul** [comment]
Unrelated to this PR, but thought I'd mention, the 3rd link in that markdown file is broken (a relative path).
(Note also that having the contributors list in the source directory can be troublesome if multiple people are working in that dir on different branches)

**Comment by Ankur-Khandelwal** [comment]
> 
> 
> Unrelated to this PR, but thought I'd mention, the 3rd link in that markdown file is broken (a relative path).
> (Note also that having the contributors list in the source directory can be troublesome if multiple people are working in that dir on different branches)

Noted!

**Comment by Ankur-Khandelwal** [comment]
@mansi59054 Closing this pull request due to inactivity over 7 days. Feel free to ping, if you want to work on this in future.

**Pull request closed without merging**
